salesforce:
  keyStore: "cert/00DHp000001ri50.jks"
  principal: "integration.user@clinnexus.com"
  tokenEndpoint: "https://login.salesforce.com/services/oauth2/token"
  audienceUrl: "https://login.salesforce.com/"


sysCmd:   
  host: "cmd-api-sys-prod-qdgaw2.emela9.usa-w1.cloudhub.io"
  port: "443"
  basePath: "/api/customer"
  CustomerId: "10032245"
  
  
  
mule:
  environment: "PROD - "

default:
 timeStamp: "2024-08-12T00:00:00+03:00"
 timeStampLeadAccount: "2024-08-26T00:00:00+03:00"
 
htmlTemplates:
  successEmail: "htmlTemplates/successEmail.template"
  errorEmail: "htmlTemplates/errorEmail.template"
  
emailSmtp:
  host: "smtp.gmail.com"
  port: "465"
  user: "helpdesk@clinnexus.com"
  from: "helpdesk@clinnexus.com"
  #to: "keerthan.bangera@accelirate.com,saujanya.verma@accelirate.com"
  to: "accelirate@clinnexus.com"
  starttls:
    key: "mail.smtp.starttls.enable"
    value: "true" 
    
sftp:
  dir: "HC_Claims/Inbound"
  archive: "New/home/archive"
  host: "s-4988316fa4374034a.server.transfer.us-east-2.amazonaws.com"
  port: "22"
  username: "production"
  key: "keys/production"
  cronExpression: "0 0 21 1/1 * ? *"
  timezone: "America/Los_Angeles"
  reconnection:
    frequency: "600000"
    attempts: "20"